--- #YAML:1.0
name:                Parse-IRCLog
version:             1.101
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
