--- #YAML:1.0
name:               Parse-IRCLog
version:            1.104
abstract:           parse internet relay chat logs
author:
    - Ricardo SIGNES <rjbs@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:    0
    Symbol:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
